version: '2'

services:
  nsd:
    image: hardware/nsd-dnssec
    container_name: nsd
    ports:
      - "172.16.238.8:10000:10000"
      - "172.16.238.8:10000:10000/udp"
    volumes:
      - /mnt/docker/nsd/conf:/etc/nsd
      - /mnt/docker/nsd/zones:/zones
      - /mnt/docker/nsd/db:/var/db/nsd
  attacker:
    container_name: coursework_attacker
    build: 
      context: ./attacker
    networks:
      net:
        ipv4_address: 172.16.238.9
    volumes:
      - ./attacker/attack.py:/attack.py:ro
  victim:
    container_name: coursework_victim
    build: 
      context: ./victim
    ports:  
      - "5000:5000"
    networks:
      net:
        ipv4_address: 172.16.238.10

networks:
  net:
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"
