version: '2.2'

services:
  # tcpdump:
  #  image: kaazing/tcpdump
  #  network_mode: "host"
  #  volumes:
  #    - ./tcpdump:/tcpdump
  bind:
    restart: always
    build: ./dns
    ports:
      - "10000:10000/tcp"
    volumes:
      - /data
    networks:
      net:
        ipv4_address: 172.16.238.8
    environment:
      - ROOT_PASSWORD=highentropy
  attacker:
    build:
      context: ./attacker
    networks:
      - net
    volumes:
      - ./attacker/attack.py:/attack.py:ro
    cpuset: "1,2,3"
  victim_web:
    container_name: coursework_victim_web
    build: 
      context: ./victim
    ports:  
      - "80:80"
    networks:
      net:
        ipv4_address: 172.16.238.100
    volumes:
      - ./victim/sniff.py:/sniff.py:ro
    working_dir: /var/www/victim.com
    extra_hosts:
      - "www.victim.com:172.16.238.100"  # same as ipv4_address
    # cpus: 0.1
    cpuset: "0"
    mem_limit: "512M"
  victim_dns:
    container_name: coursework_victim_dns
    build:
      context: ./dns
    networks:
      net:
        ipv4_address: 172.16.238.101
    # cpus: 0.01
    cpuset: "0"
    mem_limit: "512M"
    environment:
      - WEBMIN_ENABLED=false

networks:
  net:
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"
