version: '2'

services:
  tcpdump:
    image: kaazing/tcpdump
    network_mode: "host"
    volumes:
      - ./tcpdump:/tcpdump
  bind:
    container_name: coursework_dns
    restart: always
    image: sameersbn/bind:9.11.3-20190706
    ports:
      - "10000:10000/tcp"
    volumes:
      - /data
    networks:
      net:
        ipv4_address: 172.16.238.8
    environment:
      - ROOT_PASSWORD=highentropy
  attacker:
    container_name: coursework_attacker
    build: 
      context: ./attacker
    networks:
      net:
        ipv4_address: 172.16.238.9
    volumes:
      - ./attacker/attack.py:/attack.py:ro
  victim:
    container_name: coursework_victim
    build: 
      context: ./victim
    ports:  
      - "5000:5000"
    networks:
      net:
        ipv4_address: 172.16.238.10
    volumes:
      - ./victim/sniff.py:/sniff.py:ro

networks:
  net:
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"
